# Generated by Django 4.1.3 on 2023-01-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Universities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65)),
                ("country", models.CharField(max_length=120)),
                ("province", models.CharField(help_text="Viloyat", max_length=120)),
                (
                    "tuition_fees",
                    models.FloatField(help_text="kantract uchun....", max_length=123),
                ),
                (
                    "acceptance_rate",
                    models.CharField(help_text="kirish foizi", max_length=123),
                ),
                ("location", models.CharField(help_text="lacatsiyasi", max_length=120)),
                (
                    "programs",
                    models.CharField(help_text="Yonalishlari", max_length=123),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("bakalavr", "Bakalavr"),
                            ("magistraturs", "Magistraturs"),
                        ],
                        help_text="bakalrmi yoki magistraturami",
                        max_length=123,
                    ),
                ),
                ("image", models.ImageField(upload_to="univer/")),
                ("ielts", models.FloatField(help_text="Ilts darajasi")),
                ("toefle", models.IntegerField(help_text="Amerika til darsajasi")),
                (
                    "sat",
                    models.IntegerField(help_text="matematika va inglis tili darajasi"),
                ),
                ("gre", models.CharField(help_text="imtihon score", max_length=123)),
                (
                    "gmat",
                    models.FloatField(
                        help_text="magistratura uchun inglis tili va matematika",
                        max_length=123,
                    ),
                ),
                ("phone_number", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField(help_text="batafsil malumot")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
