# Generated by Django 4.1.3 on 2023-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universities",
            name="degree",
            field=models.CharField(
                choices=[("bakalavr", "Bakalavr"), ("magistratur", "Magistratur")],
                help_text="bakalrmi yoki magistraturami",
                max_length=123,
            ),
        ),
    ]
